### ISSUE TITLE
DownloadProvider

### ISSUE THREAD

**Issue by Ingvarr71** [Evolution-X-Legacy/platform_manifest#2]
Hello!
How to fix these errors?

[ 85% 63094/74068] Target Java: /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes-full-debug.jar
FAILED: /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes-full-debug.jar ) && (rm -rf /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/anno ) && (mkdir -p /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/ ) && (mkdir -p /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/anno ) && (/home/iodine71/evo/out/soong/host/linux-x86/bin/zipsync -d /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/srcjars -l /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/srcjar-list -f \"*.java\"  /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/aapt.srcjar ) && (if [ -s /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/java-source-list -o -s /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/srcjar-list ] ; then /home/iodine71/evo/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /home/iodine71/evo/out/target/common/obj/JAVA_LIBRARIES/guava_intermediates/classes-header.jar  -d /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes -s /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/anno  -source 1.8 -target 1.8 -g:source,lines  \\@/home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/java-source-list \\@/home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/srcjar-list || ( rm -rf /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes-full-debug.jar     @<(find /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/iodine71/evo/out/target/common/obj/APPS/DownloadProvider_intermediates/classes; echo \"-C /home/iodine71/evo/out/empty .\") )"
packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:155: error: cannot find symbol
        addMapping(map, DownloadManager.COLUMN_DESTINATION);
                                       ^
  symbol:   variable COLUMN_DESTINATION
  location: class DownloadManager
packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:160: error: cannot find symbol
        addMapping(map, DownloadManager.COLUMN_FILE_NAME_HINT);
                                       ^
  symbol:   variable COLUMN_FILE_NAME_HINT
  location: class DownloadManager
packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1239: error: cannot find symbol
        qb.setStrictColumns(true);
          ^
  symbol:   method setStrictColumns(boolean)
  location: variable qb of type SQLiteQueryBuilder
packages/providers/DownloadProvider/src/com/android/providers/downloads/DownloadProvider.java:1240: error: cannot find symbol
        qb.setStrictGrammar(true);
          ^
  symbol:   method setStrictGrammar(boolean)
  location: variable qb of type SQLiteQueryBuilder
4 errors

**Comment by Bit145** [comment]
Use Download provider from lineage - https://github.com/LineageOS/android_packages_providers_DownloadProvider/tree/lineage-16.0

**Comment by aayushborkar14** [comment]
I'm having same issue

**Comment by aayushborkar14** [comment]
Some other guy told me that it got fixed for him by using DownloadProvider from lineage repo but not working for me

**Comment by 4PERTURE** [comment]
@Bit145 🦀 Pie is dead 🦀

**Comment by aayushborkar14** [comment]
@4PERTURE Ok

**Comment by rerererererererererer** [comment]
@Bit145 try to use DownloadProvider from different repos.

**Comment by GeorgeV220** [comment]
@Bit145 do you find any solutions ?

**Comment by RealAkito** [comment]
@GeorgeV22-ArtlieX Here's the best solution. Build Android Q.

**Comment by GeorgeV220** [comment]
> @GeorgeV22-ArtlieX Here's the best solution. Build Android Q.

i can't build Android Q for my device.. i got errors (j4primelte or J415FN)

**Comment by bluejeans117** [comment]
@GeorgeV220 Fix those errors then lul

**Comment by RealAkito** [comment]
I don't think there's no need for this issue to stay opened as Pie is deprecated on our side and we do not support it anymore. Thanks for your interest in Evolution X Pie but it's time to move on.

- Akito

**Comment by Dargons10** [comment]
i fix it that issue for Mi Pad 1 and we have evolution-X-legacy pie!
